#pragma once

#include <cstdint>

// Burner kernels implemented in kernels_*.S (generated by tools/gen_kernels.py).
//
// All kernels share one signature:
//   iterations  number of passes to run, > 0
//   data        operand buffer, 64-byte aligned, filled by fillOperands()
//   size        size of the operand buffer in bytes
//   digest      receives 16 bytes: the XOR of the kernel's state registers
//
// The same inputs always produce the same digest, on every core.
extern "C" {

using KernelFn = void (*)(uint64_t iterations, void* data, uint64_t size, void* digest);

void stress_k_dry(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_fp32_reg(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_fp32_gemm(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_fp64_gemm(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_bf16_mmla(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_i8_mmla(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_i8_dot(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_mixed(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_fp32_stream(uint64_t iterations, void* data, uint64_t size, void* digest);
void stress_k_memcopy(uint64_t iterations, void* data, uint64_t size, void* digest);

}  // extern "C"
