"""Generates the burner kernels (app/src/main/cpp/cpu/kernels_*.S).

The kernels are long unrolled blocks of vector instructions; writing them from
a loop is what keeps a transposed register out of a 24-line block. Edit this
script, then run it from the repository root:

    python tools/gen_kernels.py
"""
import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "app/src/main/cpp/cpu"


def lines(*xs):
    return "\n".join("    " + x if x and not x.endswith(":") and not x.startswith("//") else x for x in xs)


def zero(regs):
    """movi for each register: the kernels start from zeroed accumulators."""
    return "\n".join(f"    movi v{r}.16b, #0" for r in regs)


def xor_into(dst, regs):
    """Folds registers into v<dst> for the digest."""
    return "\n".join(f"    eor v{dst}.16b, v{dst}.16b, v{r}.16b" for r in regs)


def header(title):
    return f"""// Burner kernels: {title}.
// GENERATED by tools/gen_kernels.py: edit the script, not this file.
// The calling convention and the macros are described in kernel_macros.inc.

#include "cpu/kernel_macros.inc"
"""


def fp32_reg():
    body = []
    for i in range(12):
        body.append(f"fmla v{2*i}.4s, v{2*i+1}.4s, v24.4s")
    for i in range(12):
        body.append(f"fmls v{2*i+1}.4s, v{2*i}.4s, v24.4s")
    loads = [
        "ld1 {v0.4s, v1.4s, v2.4s, v3.4s}, [x1], #64",
        "ld1 {v4.4s, v5.4s, v6.4s, v7.4s}, [x1], #64",
        "ld1 {v8.4s, v9.4s, v10.4s, v11.4s}, [x1], #64",
        "ld1 {v12.4s, v13.4s, v14.4s, v15.4s}, [x1], #64",
        "ld1 {v16.4s, v17.4s, v18.4s, v19.4s}, [x1], #64",
        "ld1 {v20.4s, v21.4s, v22.4s, v23.4s}, [x1], #64",
        "ld1 {v24.4s}, [x1]",
    ]
    return f"""
// ---------------------------------------------------------------------------
// C1: FP32 FMA on registers only.
// Twelve independent oscillators (a, b) take a symplectic Euler step per
// iteration:  a += b * m;  b -= a * m.  The state stays bounded while its
// mantissa bits keep changing, which is what keeps the multipliers busy.
// No memory traffic inside the loop.
// data: 24 state vectors followed by the multiplier vector (400 bytes).
// One iteration = 24 vector FMAs = 192 FLOP.
// ---------------------------------------------------------------------------
KERNEL stress_k_fp32_reg
    SAVE_SIMD_CALLEE
{lines(*loads)}
1:
{lines(*body)}
    subs x0, x0, #1
    b.ne 1b
{xor_into(0, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])}
    str q0, [x3]
    RESTORE_SIMD_CALLEE
    ret
END_KERNEL stress_k_fp32_reg
"""


def fp32_gemm_block(acc0=8):
    # A = v0, v1 (8 floats); B = v2, v3, v4 (12 floats); 24 accumulators.
    out = []
    acc = acc0
    for a in (0, 1):
        for b in (2, 3, 4):
            for lane in range(4):
                out.append(f"fmla v{acc}.4s, v{a}.4s, v{b}.s[{lane}]")
                acc += 1
    return out


def fp32_gemm():
    return f"""
// ---------------------------------------------------------------------------
// C2: FP32 FMA fed from L1, shaped like an SGEMM micro-kernel.
// Each 80-byte step loads A (8 floats) and B (12 floats) and performs the
// 8x12 outer product into 24 accumulators: 24 vector FMAs = 192 FLOP.
// One iteration = one pass over the buffer (size / 80 steps).
// The second half of the buffer repeats the first with A negated, so the
// accumulators swing back towards zero every pass and stay well scaled.
// ---------------------------------------------------------------------------
KERNEL stress_k_fp32_gemm
    SAVE_SIMD_CALLEE
{zero([8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])}
    mov x7, #80
    udiv x7, x2, x7
1:
    mov x5, x1
    mov x6, x7
2:
    ldp q2, q3, [x5, #32]
    ldr q4, [x5, #64]
    ldp q0, q1, [x5]
    add x5, x5, #80
{lines(*fp32_gemm_block())}
    subs x6, x6, #1
    b.ne 2b
    subs x0, x0, #1
    b.ne 1b
{xor_into(8, [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])}
    str q8, [x3]
    RESTORE_SIMD_CALLEE
    ret
END_KERNEL stress_k_fp32_gemm
"""


def fp64_gemm():
    out = []
    acc = 8
    for a in (0, 1, 2, 3):
        for b in (4, 5, 6):
            for lane in range(2):
                out.append(f"fmla v{acc}.2d, v{a}.2d, v{b}.d[{lane}]")
                acc += 1
    return f"""
// ---------------------------------------------------------------------------
// C3: FP64 FMA fed from L1.
// Each 112-byte step loads A (8 doubles) and B (6 doubles) and performs the
// 8x6 outer product into 24 accumulators: 24 vector FMAs = 96 FLOP.
// One iteration = one pass over the buffer (size / 112 steps). Mirrored
// buffer as in C2.
// ---------------------------------------------------------------------------
KERNEL stress_k_fp64_gemm
    SAVE_SIMD_CALLEE
{zero([8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])}
    mov x7, #112
    udiv x7, x2, x7
1:
    mov x5, x1
    mov x6, x7
2:
    ldp q4, q5, [x5, #64]
    ldr q6, [x5, #96]
    ldp q0, q1, [x5]
    ldp q2, q3, [x5, #32]
    add x5, x5, #112
{lines(*out)}
    subs x6, x6, #1
    b.ne 2b
    subs x0, x0, #1
    b.ne 1b
{xor_into(8, [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])}
    str q8, [x3]
    RESTORE_SIMD_CALLEE
    ret
END_KERNEL stress_k_fp64_gemm
"""


def mmla(name, code, op, arrangement, ops, what):
    out = []
    acc = 8
    for a in (0, 1, 2, 3):
        for b in (4, 5, 6, 7):
            out.append(f"{op} v{acc}.4s, v{a}.{arrangement}, v{b}.{arrangement}")
            acc += 1
    return f"""
// ---------------------------------------------------------------------------
// {code}: {what}.
// Each 128-byte step loads four A and four B vectors and issues the 16
// matrix multiply-accumulates between them into 16 accumulators.
// One instruction = {ops} operations; one iteration = one pass over the buffer
// (size / 128 steps).
// ---------------------------------------------------------------------------
KERNEL {name}
    SAVE_SIMD_CALLEE
{zero([8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])}
    lsr x7, x2, #7
1:
    mov x5, x1
    mov x6, x7
2:
    ld1 {{v4.16b, v5.16b, v6.16b, v7.16b}}, [x5], #64
    ld1 {{v0.16b, v1.16b, v2.16b, v3.16b}}, [x5], #64
{lines(*out)}
    subs x6, x6, #1
    b.ne 2b
    subs x0, x0, #1
    b.ne 1b
{xor_into(8, [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])}
    str q8, [x3]
    RESTORE_SIMD_CALLEE
    ret
END_KERNEL {name}
"""


def mixed():
    fm = fp32_gemm_block()
    ints = [
        "eor x9, x9, x10, ror #7",
        "add x10, x10, x9, lsl #3",
        "mul x11, x11, x12",
        "eor x13, x13, x11, lsr #17",
        "add x14, x14, x13",
        "eor x15, x15, x14, ror #29",
        "add x9, x9, x15",
        "str q8, [sp]",
    ]
    body = []
    for i, f in enumerate(fm):
        body.append(f)
        if i % 3 == 2 and ints:
            body.append(ints.pop(0))
    body.extend(ints)
    return f"""
// ---------------------------------------------------------------------------
// C7: Every port at once: the C2 FP32 micro-kernel with an integer hash
// chain (shift, rotate, add, xor, multiply) and a store interleaved, so the
// integer ALUs, the multiplier and the store pipe work beside the FMA pipes.
// One iteration = one pass over the buffer (size / 80 steps), 192 FLOP per
// step; the integer work is not counted.
// ---------------------------------------------------------------------------
KERNEL stress_k_mixed
    SAVE_SIMD_CALLEE
    sub sp, sp, #16
{zero([8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])}
    ldp x9, x10, [x1]
    ldp x11, x12, [x1, #16]
    ldp x13, x14, [x1, #32]
    ldr x15, [x1, #48]
    orr x12, x12, #1
    mov x7, #80
    udiv x7, x2, x7
1:
    mov x5, x1
    mov x6, x7
2:
    ldp q2, q3, [x5, #32]
    ldr q4, [x5, #64]
    ldp q0, q1, [x5]
    add x5, x5, #80
{lines(*body)}
    subs x6, x6, #1
    b.ne 2b
    subs x0, x0, #1
    b.ne 1b
{xor_into(8, [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])}
    eor x9, x9, x10
    eor x9, x9, x11
    eor x9, x9, x13
    eor x9, x9, x14
    eor x9, x9, x15
    fmov x4, d8
    eor x4, x4, x9
    mov x5, v8.d[1]
    stp x4, x5, [x3]
    add sp, sp, #16
    RESTORE_SIMD_CALLEE
    ret
END_KERNEL stress_k_mixed
"""


def fp32_stream():
    out = []
    acc = 8
    for a in (0, 1):
        for b in (2, 3):
            for lane in range(4):
                out.append(f"fmla v{acc}.4s, v{a}.4s, v{b}.s[{lane}]")
                acc += 1
    return f"""
// ---------------------------------------------------------------------------
// C8 / C9: FP32 FMA streaming its operands from a large buffer, so the
// caches (C8, L2-sized) or DRAM and the memory controller (C9) work too.
// Each 64-byte step loads A (8 floats) and B (8 floats): 16 vector FMAs =
// 128 FLOP, i.e. 2 FLOP per byte. One iteration = one pass over the buffer.
// Mirrored buffer as in C2.
// ---------------------------------------------------------------------------
KERNEL stress_k_fp32_stream
    SAVE_SIMD_CALLEE
{zero([8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])}
    lsr x7, x2, #6
1:
    mov x5, x1
    mov x6, x7
2:
    ldp q2, q3, [x5, #32]
    ldp q0, q1, [x5], #64
{lines(*out)}
    subs x6, x6, #1
    b.ne 2b
    subs x0, x0, #1
    b.ne 1b
{xor_into(8, [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])}
    str q8, [x3]
    RESTORE_SIMD_CALLEE
    ret
END_KERNEL stress_k_fp32_stream
"""


def i8_dot():
    out = []
    acc = 8
    for a in (0, 1):
        for b in (2, 3, 4):
            for lane in range(4):
                out.append(f"sdot v{acc}.4s, v{a}.16b, v{b}.4b[{lane}]")
                acc += 1
    return f"""
// ---------------------------------------------------------------------------
// C6: INT8 dot products fed from L1. Same shape as C2: each 80-byte step
// loads A (32 bytes) and B (48 bytes) and issues 24 indexed SDOTs into 24
// accumulators; one SDOT = 32 operations. One iteration = one pass over the
// buffer (size / 80 steps). Integer accumulators wrap, deterministically.
// ---------------------------------------------------------------------------
KERNEL stress_k_i8_dot
    SAVE_SIMD_CALLEE
{zero([8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])}
    mov x7, #80
    udiv x7, x2, x7
1:
    mov x5, x1
    mov x6, x7
2:
    ldp q2, q3, [x5, #32]
    ldr q4, [x5, #64]
    ldp q0, q1, [x5]
    add x5, x5, #80
{lines(*out)}
    subs x6, x6, #1
    b.ne 2b
    subs x0, x0, #1
    b.ne 1b
{xor_into(8, [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])}
    str q8, [x3]
    RESTORE_SIMD_CALLEE
    ret
END_KERNEL stress_k_i8_dot
"""


def dry():
    return """
// ---------------------------------------------------------------------------
// K0: "Dry 100%": a dependent chain of integer adds. The core reports full
// utilisation while nearly all of its execution units sit idle. It exists as
// the reference the real kernels are measured against.
// One iteration = 4 additions.
// ---------------------------------------------------------------------------
KERNEL stress_k_dry
    mov x4, #0
1:
    add x4, x4, #1
    add x4, x4, #1
    add x4, x4, #1
    add x4, x4, #1
    subs x0, x0, #1
    b.ne 1b
    stp x4, xzr, [x3]
    ret
END_KERNEL stress_k_dry
"""


def memcopy():
    return f"""
// ---------------------------------------------------------------------------
// C10: DRAM bandwidth: copies the first half of the buffer onto the second
// half with 128-bit loads and stores, 64 bytes per step. Regular stores make
// the memory system read each destination line before writing it, which
// adds traffic. The digest folds every loaded vector, so it depends only on
// the source half. One iteration = size bytes moved (half read, half written).
// ---------------------------------------------------------------------------
KERNEL stress_k_memcopy
    SAVE_SIMD_CALLEE
{zero([8,9,10,11])}
    lsr x7, x2, #7
    lsr x8, x2, #1
1:
    mov x5, x1
    add x4, x1, x8
    mov x6, x7
2:
    ldp q0, q1, [x5]
    ldp q2, q3, [x5, #32]
    add x5, x5, #64
    stp q0, q1, [x4]
    stp q2, q3, [x4, #32]
    add x4, x4, #64
    eor v8.16b, v8.16b, v0.16b
    eor v9.16b, v9.16b, v1.16b
    eor v10.16b, v10.16b, v2.16b
    eor v11.16b, v11.16b, v3.16b
    subs x6, x6, #1
    b.ne 2b
    subs x0, x0, #1
    b.ne 1b
{xor_into(8, [9,10,11])}
    str q8, [x3]
    RESTORE_SIMD_CALLEE
    ret
END_KERNEL stress_k_memcopy
"""


def emit(name, text):
    (OUT / name).write_text(text, encoding="ascii", newline="\n")


emit(
    "kernels_fp.S",
    header("floating point")
    + fp32_reg() + fp32_gemm() + fp64_gemm()
    + mmla("stress_k_bf16_mmla", "C4", "bfmmla", "8h", 32, "BF16 matrix multiply-accumulate (BFMMLA) fed from L1")
    + mixed() + fp32_stream(),
)
emit(
    "kernels_int.S",
    header("integer")
    + dry()
    + mmla("stress_k_i8_mmla", "C5", "smmla", "16b", 64, "INT8 matrix multiply-accumulate (SMMLA) fed from L1")
    + i8_dot(),
)
emit("kernels_mem.S", header("memory") + memcopy())
print("written")
